### ISSUE TITLE
Fix USB panel mount

### ISSUE THREAD

**Issue by vegro90** [sloydsalen/Dingsen#6]
Some examples:
Like this one due to te robust mount with screw holes (http://www.l-com.com/usb-usb-type-a-coupler-female-bulkhead-male-12-in)
Could be nice, but need to use a male connector on the inside (https://www.kjell.com/no/produkter/data-og-nettverk/nettverk/installasjonsmateriell/keystone/keystone-usb-2-0-modul-p95428)
This does not need an extra connector inside. By splitting it in two we also get two female connectors for different projects. (https://www.kjell.com/no/produkter/data-og-nettverk/nettverk/installasjonsmateriell/keystone/keystone-usb-2-0-modul-24-cm-p95429)

**Comment by vegro90** [comment]
Another possibility is to integrate this with or without a 3Dprinted mount.
https://www.elfadistrelec.no/en/socket-vertical-usb-4p-tht-wuerth-elektronik-614004185023/p/30049710?q=usb+2+socket&page=11&origPos=11&origPageSize=25&simi=95.91
Might be nice to print a circular mount so it's easier to create a mounting hole in the box. (Always a pain to carve out small square holes)

**Comment by nanonerd1** [comment]
What about:
http://www.ebay.com/itm/Boat-Car-Dashboard-Moto-Flush-Mount-Panel-USB-2-0-3-5mm-AUX-Lead-Extension-Cable-/272625615768?var=&hash=item3f79c0c398:m:mndinpqj91ApPiBF_52peRA

**Comment by vegro90** [comment]
Looks really nice @nanonerd1 ! Then only need to drill one extra hole in the project box!
Could also be nice with a USB mini Type B male contact for the end going into the Arduino mini. Like this one: 
http://www.ebay.com/itm/10PCS-Mini-USB-10-Pin-Male-Plug-Socket-Connector-With-Plastic-Cover-/201727093960?hash=item2ef7df2cc8:g:FwQAAOSwiONYNZu2

**Comment by nanonerd1** [comment]
Or: ELFA:
Art.nr.  300-30-430 
Art.nr.  300-17-845 
or similar... Feel free to make a list of Things at Elfa that is desired, including the of/off switch... and I will Place an order.

**Comment by vegro90** [comment]
I will look into that!
Guess I can try to create a clone of the Dashboard mount with both AUX and USB by printing the socket myself. Just need to get the sockets first (Female USB and male mini-usb)
